# (C) Copyright 2022-23 Hewlett Packard Enterprise Development LP

openapi: 3.0.0
info:
  title: Gateway Download Manager
  description: REST API for Gateway Download Manager
  version: "v1.0.0"
  contact:
    name: Team Udaan
    email: glcs.team-udaan@hpe.com
servers:
  - url: https://localhost:8188/
    description: local
  - url: https://gateway-api.ops.hpedevops.net/
    description: development
  - url: https://gateway-api.private.greenlake.hpe-gl-intg.com/
    description: integration
  - url: https://gateway-api.privatecloud.greenlake.hpe.com/
    description: production
tags:
  - name: Info
    description: General information of Gateway Service
  - name: Deployment
    description: Deployment defines a Gateway Deployment for a Tenant
  - name: OSB
    description: Gateway OSB APIs

security:
  - bearerAuth: []

paths:
  /v2/version:
    get:
      operationId: GetVersion
      tags:
        - Info
      summary: Get Version
      description: Version of Gateway Service
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/BrokerAPIVersion'
      responses:
        '200':
          description: Version and Build number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
        '400':
          description: "Missing headers to get API version"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '401':
          description: "Unauthorized to get API version"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '403':
          description: "Forbidden to get API version"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
        '500':
          description: "Failed to get API version"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
