# (C) Copyright 2023 Hewlett Packard Enterprise Development LP

openapi: 3.0.0
info:
  title: Gateway Download Manager
  description: REST API for Gateway Download Manager
  version: "v1.0.0"
  contact:
    name: Team Udaan
    email: glcs.team-udaan@hpe.com
servers:
  - url: https://localhost:8188/
    description: local
tags:
  - name: Info
    description: General information of Gateway Download Manager

paths:
  /status:
    get:
      tags:
        - Info
      summary: Get Status
      description: Status of Gateway Download Manager API Service
      responses:
        '200':
          description: Status of Gateway Download Manager api service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /check-artifact:
    post:
      tags:
        - Info
      summary: Check Artifact
      description: Check if an artifact has been pushed
      parameters:
        - $ref: '#/components/parameters/ArtifactName'
      responses:
        '200':
          description: "Presence of artifact in artifactories."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckArtifact'
              
        '400':
          description: "ArtifactName parameter missing from the request."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '500':
          description: "Internal Server Error - Failed to check for artifact"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /push-artifacts:
    post:
      tags:
        - Info
      summary: "Push Artifact"
      description: "Queue the Download manager to pull a list of artifacts from S3 bucket and push to respective artifactories(harbor/pulp ) "
      parameters:
        - $ref: '#/components/parameters/PushArtifacts'
      responses:
        '200':
          description: "Successfully triggered download-manager to push artifacts."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        '400':
          description: "Improper request body."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '401':
          description: "Incorrect S3 credentials."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '500':
          description: Internal Server Error - Failed to queue artifacts in download-manager
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'


components:
  schemas:
    Status:
      type: object
      description: Service Status
      required:
        - status
      properties:
        status:
          type: string
          example: success
    CheckArtifact:
      type: object
      description: "Response from api-service for checking if an artifact is pushed successfully."
      properties:
        Artifact: 
          type: string
          example: morpheus-appliance-5.4.10-2.zip
        Exists:
          type: boolean
          example: "true"

    BadRequestError:
      type: object
      description: Bad Request Error
      required:
        - code
        - msg
        - error
      properties:
        code:
          type: integer
          example: 400
          description: HTTP Status Code
        msg:
          type: string
          example:  A required parameter is missing from rrequest header.
          description: Bad Request
        error:
          type: string
          example: Bad Request
          description: Bad Request

    UnauthorizedError:
      type: object
      description: Unauthorized Error
      required:
        - code
        - msg
        - error
      properties:
        code:
          type: integer
          example: 401
          description: HTTP Status Code
        msg:
          type: string
          example: User Unauthorized to perform above action
          description: Unauthorized
        error:
          type: string
          example: Unauthorized
          description: Unauthorized

    InternalServerError:
      type: object
      description: Internal Server Error
      required:
        - code
        - msg
        - error
      properties:
        code:
          type: integer
          example: 500
          description: HTTP Status Code
        msg:
          type: string
          example: Failure during handling of request
          description: Internal Server Error
        error:
          type: string
          example: Internal Server Error
          description: Internal Server Error

    S3Creds:
      type: object
      description: "S3 keys required for operation"
      properties:
        AWS_ACCESS_KEY_ID:
          type: string
          example: "AK12AZXJR2MUTEVHI"
        AWS_SECRET_ACCESS_KEY:
          type: string
          example: "qmPvwfjs4714tqBfjs47JqmPvw14tqBJ4714tq"
        AWS_DEFAULT_REGION:
          type: string
          example: "us-west-2"

    PushArtifactParam:
      type: object
      description: "schema for push artifact parameters"
      properties:
        S3Creds:
          $ref: '#/components/schemas/S3Creds'
        ArtifactList:
          type: array
          items: 
            type: string

      required: [S3Creds, ArtifactList]
    
    CheckArtifactParam:
      type: object
      description: "schema for check artifact parameters"
      properties:
        Name:
          type: string
          example: morpheus-appliance-5.4.10-2.zip
      required: [ArtifactName]
          

  parameters:
    PushArtifacts:
      name: PushArtifacts
      in: header
      schema:
        $ref: '#/components/schemas/PushArtifactParam'
    ArtifactName: 
      name: ArtifactName
      in: header
      schema:
        $ref: '#/components/schemas/CheckArtifactParam'
      



