# (C) Copyright 2022-23 Hewlett Packard Enterprise Development LP

openapi: 3.0.0
info:
  title: Gateway Download Manager
  description: REST API for Gateway Download Manager
  version: "v1.0.0"
  contact:
    name: Team Udaan
    email: glcs.team-udaan@hpe.com
servers:
  - url: https://localhost:8188/
    description: local
tags:
  - name: Info
    description: General information of Gateway Download Manager

security:
  - bearerAuth: []

paths:
  /status:
    get:
      # operationId: GetVersion
      tags:
        - Info
      summary: Get Status
      description: Status of Gateway Download Manager
      responses:
        '200':
          description: Status of Gateway Download Manager api service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
        '400':
          description: "Missing headers to get API version"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '401':
          description: "Unauthorized to get API version"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '403':
          description: "Forbidden to get API version"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
        '500':
          description: "Failed to get API version"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /check-artifact:
    post:
      tags:
        - Info
      summary: Check Artifact
      description: Check if an artifact has been pushed
      parameters:
        $ref: '#components/parameter/ArtifactName'
      responses:
        '200':
          description: "artifact puhsed"
          content:
            application/json:
              type: object
              description: "200 response"
              properties:
                Artifact: 
                  type: string
                  example: morpheus-appliance-5.4.10-2.zip
                Exists:
                  type: bool
                  example: "true"
        '500':
          description: "st 500"
          content:
          # contnogflanlafnlanf
    
    /push-artifacts:
      post:
        tags:
          - Info
        summary: "Push Artifact"
        description: "some description"
        parameters:
          $ref: "#/parameters/PushArtifacts"
        responses:
          '201':
            



components:
  schemas:
    CheckArtifactResponse:
      type: object
      description: "schema for check artifact response"
      properties:
        artifact-name : 
          type: string
          example: morpheus-appliance-5.4.10-2.zip

    S3Creds:
      type: object
      description: "S3 keys required for operation"
      properties:
        AWS_ACCESS_KEY_ID:
          type: string
          example: "fjajlfjlajfa"
        AWS_SECRET_ACCESS_KEY:
          type: string
          example: "jflajfjodifdf"
        AWS_DEFAULT_REGION:
          type: string
          example: "us-west-2"

    PushArtifactParam:
      type: object
      description: ""
      properties:
        S3Creds:
          type: object
          $ref: "#/components/S3Creds"
        ArtifactList:
          type: array
          items: 
            type: string

      required: [S3Creds, ArtifactList]

    



  parameter:
    ArtifactName: 
      name: ArtifactName
      in: body
      required: true
      type: string
    PushArtifacts:
      name: PushArtifacts
      in: body
      requied: true
      schema:
        $ref: "#/components/schemas/PushArtifactParam"
      
